# octopus_lab Home Assistant

...

# display8
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

sensor:
  - platform: homeassistant
    name: "BTC/USD"
    id: ident_btc
    entity_id: sensor.btc_usd

display:
  - platform: max7219
    cs_pin: GPIO5
    num_chips: 1
    update_interval: 1000ms
    lambda: |-
      it.set_intensity(5);
      it.printf("%8.0f", id(ident_btc).state);